version: "3"
services:
  web:
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    image: xstake
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app/
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "data:/var/lib/postgresql/data"
volumes:
  data:
