version: "3"
services:
  web:
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis
    image: xstake
    depends_on:
      - db
      - redis
    volumes:
      - ./:/usr/src/app/
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "data:/var/lib/postgresql/data"
  db:
    image: redis:6.2-alpine

volumes:
  data:
